# Challenge
Write a function named "Challenge" that throws an error with a message "Successful throw!"
